CREATE TABLE IF NOT EXISTS chats (
    id SERIAL PRIMARY KEY,
    tg_chat_id INTEGER NOT NULL UNIQUE,
    user_id INTEGER NOT NULL UNIQUE,
    cdate TIMESTAMP NOT NULL DEFAULT NOW(),
    udate TIMESTAMP NOT NULL DEFAULT NOW()
);