version: '2'
services:
  bot:
    build:
      context: .   
    container_name: bot-app
    env_file:
    - .env
    depends_on: 
      - postgresql
    restart_policy:
      condition: on-failure
  postgresql:    
    build:
      context: ./postgresql    
    env_file:
    - ./postgresql/.env
    container_name: bot-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  

networks:
  default:
    external:
      name: 15x4
  