version: '3.5'
services:
  bot:
    image: bot:latest
    build:
      context: .   
    container_name: bot-app
    env_file:
    - .env
    depends_on: 
      - postgresql
    restart: on-failure
  postgresql:
    image: bot-db:latest
    build:
      context: ./postgresql    
    env_file:
    - ./postgresql/.env
    container_name: bot-db
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/docker/volumes/15x4bot_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  default:
    external:
      name: 15x4
  
