version: '2'
services:
  bot:
    build:
      context: .   
    container_name: bot-app
    env_file:
    - .env
    depends_on: 
      - postgresql
  postgresql:
    build:
      context: ./postgresql      
    container_name: bot-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:      

  