version: '2'
services:
  reminder:
    build:
      context: .   
    container_name: reminder
    env_file:
    - .env
    depends_on: 
      - postgresql
  postgresql:
    build:
      context: ./postgresql      
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data