version: '3.5'
services:
  bot:
    image: bot:latest
    build:
      context: .   
    container_name: bot-app
    env_file:
    - .env
    depends_on: 
      - postgresql
    restart: on-failure
  postgresql:
    image: postgres:11
    env_file:
    - ./postgresql/.env
    container_name: bot-db
    expose:
      - "5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  pgdata:  

networks:
  default:
    external:
      name: 15x4
  
